fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-aws-credentials
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/leoll2/copyright_notice_precommit
    rev: 0.1.1
    hooks:
      - id: copyright-notice
        args: [--notice=LICENSE, --h]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args:
          - "--configfile"
          - .codestyle/.bandit
          - "-ll"
          - "-ii"
  - repo: https://github.com/crate-ci/typos
    rev: v1.1.9
    hooks:
      - id: typos
        args:
          - "--config"
          - .codestyle/.typos.toml

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=120]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=120
          - --include='\.pyi?$'

          - --exclude="""\.git | \.__pycache__| \.hg| \.mypy_cache| \.tox| \.venv| dist"""

        language: system

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-isort
          - flake8-polyfill
          - flake8-pytest
          - flake8-quotes
          - flake8-typing-imports
          - yesqa
        args:
          - "--max-line-length=120"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        exclude: ^(docs/)

  - repo: https://github.com/pycqa/pylint
    rev: v2.14.1
    hooks:
      - id: pylint
        args:
          - --max-line-length=120
          - --ignore-imports=yes
          - -d duplicate-code
          - --disable=E0401,R1710

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/openstack/bashate
    rev: 2.1.0
    hooks:
      - id: bashate
        args:
          - -i
          - E006

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
