fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-aws-credentials
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=88
          - --include='\.pyi?$'

          - --exclude="""\.git | \.__pycache__| \.hg| \.mypy_cache| \.tox| \.venv|
            dist"""

        language: system

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        args:
          - "--max-line-length=88"

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        exclude: ^(docs/)

  - repo: https://github.com/pycqa/pylint
    rev: v2.14.0
    hooks:
      - id: pylint
        args:
          - --max-line-length=88
          - --ignore-imports=yes
          - -d duplicate-code
          - --disable=E0401,R1710
